// data.js — Verified Academic & Institutional Data for Hadhramout Center
// Strictly verified from hadramout.center primary archives and publications.

const HC_DATA = {
  institution: {
    nameAr: "مركز حضرموت للدراسات التاريخية والتوثيق والنشر",
    nameEn: "Hadhramout Center for Historical Studies, Documentation and Publishing",
    shortNameAr: "مركز حضرموت",
    shortNameEn: "Hadhramout Center",
    taglineAr: "مرجعٌ علميٌّ مستقل لتوثيق تاريخ حضرموت وتراثها وحضارتها",
    taglineEn: "An independent scholarly authority documenting the history, heritage, and civilization of Hadhramout",
    foundedYear: 2015,
    locationAr: "المكلا، حضرموت، الجمهورية اليمنية",
    locationEn: "Mukalla, Hadhramout, Republic of Yemen",
    addressAr: "عمارة باشريف، بجانب مسجد الغالبي، حي الشهيد خالد، المكلا",
    addressEn: "Bashareef Building, Beside Al-Ghalibi Mosque, Al-Shaheed Khaled Quarter, Mukalla",
    email: "info@hadramout.center",
    phoneYe: "+967 773570194",
    phoneSa: "+966 556408983",
    social: {
      x: "https://x.com/HadramoutCenter",
      facebook: "https://www.facebook.com/hadramout.center/",
      instagram: "https://instagram.com/hadramoutcenter",
      telegram: "https://t.me/hadramoutcenter",
      youtube: "https://www.youtube.com/@hadramoutcenter"
    },
    leadership: [
      {
        nameAr: "أ. د. عبد الله سعيد الجعيدي",
        nameEn: "Prof. Dr. Abdullah Saeed Al-Ja'idi",
        roleAr: "رئيس المركز",
        roleEn: "President of the Center",
        bioAr: "أستاذ التاريخ الحديث والمعاصر بجامعة حضرموت، وباحث ومؤرخ بارز له العديد من المؤلفات والدراسات التوثيقية لتاريخ حضرموت وجنوب الجزيرة العربية.",
        bioEn: "Professor of Modern History at Hadhramout University, leading historian and author of numerous landmark studies on Hadhramout and South Arabian history."
      },
      {
        nameAr: "أ. محمد سالم بن علي جابر",
        nameEn: "Mr. Mohammed Salem bin Ali Jaber",
        roleAr: "رئيس مجلس الإدارة",
        roleEn: "Chairman of the Board of Directors",
        bioAr: "راعي ثقافي وباحث مهتم بالتوثيق التراثي ودعم البحث العلمي التاريخي والمشاريع المعرفية في حضرموت.",
        bioEn: "Cultural patron and researcher committed to heritage documentation, academic historical research, and intellectual development in Hadhramout."
      }
    ],
    departments: [
      {
        nameAr: "قسم الدراسات والبحوث التاريخية",
        nameEn: "Department of Historical Studies & Research",
        descAr: "يتولى إعداد وتنفيذ الأبحاث المنهجية وتحقيق المخطوطات والوثائق ودراسة الوقائع التاريخية لحضرموت.",
        descEn: "Leads academic historical inquiries, manuscript verification, and in-depth research on Hadhrami heritage."
      },
      {
        nameAr: "قسم التوثيق والأرشيف والمخطوطات",
        nameEn: "Department of Documentation, Archives & Manuscripts",
        descAr: "يختص بجمع وتصنيف وفهرسة الوثائق الأهلية والحكومية التاريخية والمراسلات والخرائط النادرة.",
        descEn: "Specializes in collecting, cataloging, and preserving historical family and official documents, deeds, and rare maps."
      },
      {
        nameAr: "قسم الترجمة والنشر العلمي",
        nameEn: "Department of Translation & Scholarly Publishing",
        descAr: "يشرف على إصدار مجلة حضرموت الثقافية وسلسلة الكتب المحكّمة وترجمة كتابات الرحالة والمستشرقين.",
        descEn: "Oversees the publication of the Cultural Magazine, academic monographs, and translations of orientalist travel accounts."
      },
      {
        nameAr: "قسم الفعاليات والمؤتمرات العلمية",
        nameEn: "Department of Academic Symposia & Conferences",
        descAr: "ينظم المؤتمرات العلمية المحكّمة ومنتدى عميد الوفاء الثقافي والمحاضرات الفكرية الدورية.",
        descEn: "Coordinates biennial scholarly conferences, the Ameed Al-Wafa Cultural Forum, and academic panel lectures."
      }
    ]
  },

  magazines: [
    {
      id: "mag-40",
      issueNumber: 40,
      titleAr: "مجلة حضرموت الثقافية — العدد 40",
      titleEn: "Hadramout Cultural Magazine — Issue 40",
      dateAr: "شتاء / ربيع 2026",
      dateEn: "Winter / Spring 2026",
      featured: true,
      coverImage: "https://files.hadramout.center/media/2026/09/image-6.png",
      summaryAr: "صدر العدد الأربعون محتوياً على ملف خاص حول الهجرة الحضرمية وأثرها في بلدان المهجر الشرقي، إلى جانب دراسات تاريخية وقراءات وثائقية وتراجم لأعلام الفكر.",
      summaryEn: "Issue 40 features an extensive file on the Hadhrami diaspora in Southeast Asia, alongside archival studies, historical document analyses, and biographical tributes.",
      articlesCount: 14,
      pages: 184,
      pdfUrl: "https://hadramout.center/magazines/10024",
      editorialBoardAr: "نخبة من أساتذة التاريخ والآداب بجامعة حضرموت وجامعات عربية",
      editorialBoardEn: "Distinguished faculty from Hadhramout University and regional academic institutions"
    },
    {
      id: "mag-39",
      issueNumber: 39,
      titleAr: "مجلة حضرموت الثقافية — العدد 39",
      titleEn: "Hadramout Cultural Magazine — Issue 39",
      dateAr: "خريف 2025",
      dateEn: "Autumn 2025",
      featured: false,
      coverImage: "https://files.hadramout.center/media/2025/12/غلاف-المؤتمر-الخامس-التاريخ-والمؤرخون-الحضارمة3-scaled.jpg",
      summaryAr: "ملف حول تاريخ الصحافة الحضرمية المبكرة، ودراسات في النقوش اليمنية القديمة وشواهد الآثار في وادي حضرموت.",
      summaryEn: "Features studies on early Hadhrami journalism, epigraphic discoveries, and ancient South Arabian inscriptions in Wadi Hadhramout.",
      articlesCount: 12,
      pages: 172,
      pdfUrl: "https://hadramout.center/magazines"
    },
    {
      id: "mag-38",
      issueNumber: 38,
      titleAr: "مجلة حضرموت الثقافية — العدد 38",
      titleEn: "Hadramout Cultural Magazine — Issue 38",
      dateAr: "صيف 2025",
      dateEn: "Summer 2025",
      featured: false,
      coverImage: "https://files.hadramout.center/media/2025/12/أبحاث-في-تاريخ-السلطنة-القعيطية3-scaled.jpg",
      summaryAr: "دراسات في العمارة الطينية بشبام وتريم، وبحوث في الوثائق الوقفية التاريخية وعلاقات حضرموت بموانئ البحر العربي.",
      summaryEn: "Research on the mud-brick architecture of Shibam and Tarim, historical waqf endowments, and Indian Ocean coastal connections.",
      articlesCount: 15,
      pages: 196,
      pdfUrl: "https://hadramout.center/magazines"
    }
  ],

  publications: [
    {
      id: "bk-9882",
      slug: "hadhrami-grammarians",
      titleAr: "جهود علماء حضرموت النحوية – دراسة وتحقيق",
      titleEn: "Grammatical Contributions of Hadhrami Scholars: A Study and Critical Edition",
      authorAr: "د. خالد سعيد باوزير",
      authorEn: "Dr. Khaled Saeed Bawazir",
      category: "linguistics",
      categoryAr: "التراث اللغوي والنحوي",
      categoryEn: "Linguistics & Heritage",
      year: 2026,
      hijriYear: 1447,
      pages: 320,
      isbn: "978-9923-81-012-4",
      coverImage: "https://files.hadramout.center/media/2026/02/img20260209_20543382-scaled.jpg",
      abstractAr: "دراسة استقصائية معمقة ترصد النتاج النحوي واللغوي لعلماء حضرموت عبر العصور، مع تحقيق لمخطوطات نحوية نادرة تكشف عن خصوصية المنهج التعليمي والتأليفي في الحواضر العلمية كـ تريم والغرفة وغيل باوزير.",
      abstractEn: "An exhaustive academic study tracing the grammatical and linguistic contributions of Hadhrami scholars through the centuries, featuring critical editions of previously unpublished manuscripts.",
      citationAPA: "باوزير، خ. س. (2026). جهود علماء حضرموت النحوية: دراسة وتحقيق. المكلا: مركز حضرموت للدراسات التاريخية والتوثيق والنشر.",
      citationChicago: "باوزير، خالد سعيد. جهود علماء حضرموت النحوية: دراسة وتحقيق. المكلا: مركز حضرموت للدراسات التاريخية والتوثيق والنشر، 2026.",
      citationMLA: "باوزير، خالد سعيد. جهود علماء حضرموت النحوية: دراسة وتحقيق. مركز حضرموت للدراسات التاريخية والتوثيق والنشر، 2026.",
      featured: true
    },
    {
      id: "bk-9876",
      slug: "papers-in-broom-history",
      titleAr: "أوراق في تاريخ بروم",
      titleEn: "Papers on the History of Broom: Port and Civilization",
      authorAr: "أ. محمد عبد القادر بامطرف",
      authorEn: "Prof. Mohammed Abdulqader Ba-Matraf",
      category: "ports-trade",
      categoryAr: "الموانئ والتاريخ المحلي",
      categoryEn: "Maritime Ports & Local History",
      year: 2026,
      hijriYear: 1447,
      pages: 248,
      isbn: "978-9923-81-011-7",
      coverImage: "https://files.hadramout.center/media/2026/02/img20260211_21160330-scaled.jpg",
      abstractAr: "كتاب يؤرخ لميناء ومدينة بروم التاريخية الواقعة على ساحل بحر العرب، مسلطاً الضوء على دورها كمرفأ طبيعي آمن لسفن التجارة والملاحة الشراعية، وأهميتها العسكرية والمدنية في عهود الدول المتعاقبة.",
      abstractEn: "An archival study of the historic maritime port of Broom on the Arabian Sea, detailing its role as a natural harbor for ancient dhow fleets and commercial convoys.",
      citationAPA: "بامطرف، م. ع. (2026). أوراق في تاريخ بروم. المكلا: مركز حضرموت للدراسات التاريخية والتوثيق والنشر.",
      citationChicago: "بامطرف، محمد عبد القادر. أوراق في تاريخ بروم. المكلا: مركز حضرموت للدراسات التاريخية والتوثيق والنشر، 2026.",
      citationMLA: "بامطرف، محمد عبد القادر. أوراق في تاريخ بروم. مركز حضرموت للدراسات التاريخية والتوثيق والنشر، 2026.",
      featured: true
    },
    {
      id: "bk-9308",
      slug: "hadhrami-historians-20th-century",
      titleAr: "التاريخ والمؤرخون الحضارمة في النصف الأول من القرن العشرين",
      titleEn: "Hadhrami History and Historians in the First Half of the 20th Century",
      authorAr: "بحوث المؤتمر العلمي الخامس (مجموعة باحثين)",
      authorEn: "Proceedings of the 5th Scientific Conference (Various Authors)",
      category: "sultanates",
      categoryAr: "أعمال المؤتمرات العلمية",
      categoryEn: "Conference Proceedings",
      year: 2025,
      hijriYear: 1447,
      pages: 580,
      isbn: "978-9923-81-008-7",
      coverImage: "https://files.hadramout.center/media/2025/12/غلاف-المؤتمر-الخامس-التاريخ-والمؤرخون-الحضارمة3-scaled.jpg",
      abstractAr: "المجلد التوثيقي الكامل لأعمال وأبحاث المؤتمر العلمي الخامس الذي نظمه المركز، جامعاً أكثر من عشرين دراسة محكمة حول مناهج المؤرخين الحضارمة كالحداد، وباحنان، وابن عبيداللاه السقاف، والبار، والسلطان غالب القعيطي.",
      abstractEn: "Complete peer-reviewed proceedings of the 5th Academic Conference, gathering over 20 rigorous studies examining the historiographical methods of leading 20th-century Hadhrami scholars.",
      citationAPA: "مركز حضرموت للدراسات التاريخية. (2025). التاريخ والمؤرخون الحضارمة في النصف الأول من القرن العشرين. المكلا: منشورات المركز.",
      citationChicago: "مركز حضرموت للدراسات التاريخية والتوثيق والنشر. التاريخ والمؤرخون الحضارمة في النصف الأول من القرن العشرين. المكلا: منشورات المركز، 2025.",
      citationMLA: "مركز حضرموت للدراسات التاريخية والتوثيق والنشر. التاريخ والمؤرخون الحضارمة في النصف الأول من القرن العشرين. 2025.",
      featured: true
    },
    {
      id: "bk-9126",
      slug: "hadhrami-marketing-commerce",
      titleAr: "التسويق الحضرمي عبر العصور بين المهارة والهوية",
      titleEn: "Hadhrami Commerce & Marketing Across Ages: Skill and Identity",
      authorAr: "د. عبد العزيز سعيد بن حبتور",
      authorEn: "Dr. Abdulaziz Saeed Bin Habtoor",
      category: "ports-trade",
      categoryAr: "التاريخ الاقتصادي والتجاري",
      categoryEn: "Economic & Trade History",
      year: 2025,
      hijriYear: 1447,
      pages: 288,
      isbn: "978-9923-81-005-6",
      coverImage: "https://files.hadramout.center/media/2025/12/التسويق-الحضرمي-عبر-العصور3-scaled.jpg",
      abstractAr: "قراءة تحليلية في تطور المنهج التجاري والتسويقي الحضرمي في الداخل وبلدان المهجر (إندونيسيا، سنغافورة، الهند، الحجاز، وشرق أفريقيا)، مبرزاً أثر الصدق والأمانة في بناء شبكات التجارة الدولية.",
      abstractEn: "An analytical study of the development of Hadhrami mercantile acumen and commercial networks across Southeast Asia, India, the Arabian Peninsula, and the East African coast.",
      citationAPA: "بن حبتور، ع. س. (2025). التسويق الحضرمي عبر العصور بين المهارة والهوية. المكلا: مركز حضرموت.",
      citationChicago: "بن حبتور، عبد العزيز سعيد. التسويق الحضرمي عبر العصور بين المهارة والهوية. المكلا: مركز حضرموت للدراسات التاريخية، 2025.",
      citationMLA: "بن حبتور، عبد العزيز سعيد. التسويق الحضرمي عبر العصور بين المهارة والهوية. مركز حضرموت، 2025.",
      featured: true
    },
    {
      id: "bk-9124",
      slug: "hadhramout-ingrams-wwii",
      titleAr: "حضرموت .. من صلح إنجرامس إلى الحرب العالمية الثانية",
      titleEn: "Hadhramout: From Ingrams Peace to World War II",
      authorAr: "د. عبد الله سعيد الجعيدي",
      authorEn: "Prof. Dr. Abdullah Saeed Al-Ja'idi",
      category: "sultanates",
      categoryAr: "التاريخ السياسي المعاصر",
      categoryEn: "Modern Political History",
      year: 2025,
      hijriYear: 1447,
      pages: 364,
      isbn: "978-9923-81-004-9",
      coverImage: "https://files.hadramout.center/media/2025/12/غلاف-محاضرات-انجرامز3-scaled.jpg",
      abstractAr: "دراسة وثائقية تتناول مرحلة حاسمة من تاريخ حضرموت الحديث شملت معاهدات الصلح القبلي التي أشرف عليها المستشار البريطاني هارولد إنجرامس، وتداعيات المجاعة والحرب العالمية الثانية على التركيبة الاقتصادية والسياسية.",
      abstractEn: "A primary documentary study analyzing the political treaties orchestrated by British advisor Harold Ingrams, the Great Famine, and the wartime geopolitical impacts on the Qu'aiti and Kathiri states.",
      citationAPA: "الجعيدي، ع. س. (2025). حضرموت: من صلح إنجرامس إلى الحرب العالمية الثانية. المكلا: مركز حضرموت.",
      citationChicago: "الجعيدي، عبد الله سعيد. حضرموت: من صلح إنجرامس إلى الحرب العالمية الثانية. المكلا: مركز حضرموت للدراسات التاريخية، 2025.",
      citationMLA: "الجعيدي، عبد الله سعيد. حضرموت: من صلح إنجرامس إلى الحرب العالمية الثانية. مركز حضرموت، 2025.",
      featured: true
    },
    {
      id: "bk-9120",
      slug: "al-uqla-inscriptions-archaeology",
      titleAr: "العقلة دراسة تاريخية من خلال الشواهد الأثرية والنقشية",
      titleEn: "Al-Uqlah: A Historical Study Through Epigraphic and Archaeological Evidence",
      authorAr: "د. رياض أحمد بامحسون",
      authorEn: "Dr. Riad Ahmed Bamahsoon",
      category: "archaeology",
      categoryAr: "الآثار والنقوش القديمة",
      categoryEn: "Archaeology & Epigraphy",
      year: 2025,
      hijriYear: 1447,
      pages: 216,
      isbn: "978-9923-81-003-2",
      coverImage: "https://files.hadramout.center/media/2025/12/غلاف-كتاب-العقلة-3-scaled.jpg",
      abstractAr: "دراسة متخصصة في موقع العقلة الأثري قرب شبوة، تسبر غور النقوش المسندية التي وثقت طقوس تتويج ملوك حضرموت القدماء واصطياد الوعول والمراسيم الدينية في العصور السابقة للإسلام.",
      abstractEn: "Specialized epigraphic research examining the rock inscriptions of the ancient site of Al-Uqlah near Shabwa, documenting coronation rituals and sacred royal ceremonies of the Kings of Hadhramout.",
      citationAPA: "بامحسون، ر. أ. (2025). العقلة دراسة تاريخية من خلال الشواهد الأثرية والنقشية. المكلا: مركز حضرموت.",
      citationChicago: "بامحسون، رياض أحمد. العقلة دراسة تاريخية من خلال الشواهد الأثرية والنقشية. المكلا: مركز حضرموت للدراسات التاريخية، 2025.",
      citationMLA: "بامحسون، رياض أحمد. العقلة دراسة تاريخية من خلال الشواهد الأثرية والنقشية. مركز حضرموت، 2025.",
      featured: false
    },
    {
      id: "bk-9122",
      slug: "quaiti-sultanate-studies",
      titleAr: "أبحاث في تاريخ السلطنة القعيطية الحضرمية",
      titleEn: "Studies in the History of the Qu'aiti Hadhrami Sultanate",
      authorAr: "نخبة من المؤرخين والباحثين",
      authorEn: "Symposium of Historians and Scholars",
      category: "sultanates",
      categoryAr: "تاريخ السلطنات والسياسة",
      categoryEn: "Sultanate History",
      year: 2025,
      hijriYear: 1447,
      pages: 412,
      isbn: "978-9923-81-002-5",
      coverImage: "https://files.hadramout.center/media/2025/12/أبحاث-في-تاريخ-السلطنة-القعيطية3-scaled.jpg",
      abstractAr: "سلسلة من الأوراق العلمية التي تتناول النظام الإداري والعسكري والمالي للسلطنة القعيطية (1881 - 1967)، وبناء المؤسسات الحديثة كالقضاء والبريد والجمارك والمناهج التعليمية النظامية في المكلا والشحر.",
      abstractEn: "Scholarly papers examining the administrative, military, and institutional modernization of the Qu'aiti State (1881–1967), including judiciary systems, postal infrastructure, and modern schooling.",
      citationAPA: "مركز حضرموت للدراسات التاريخية. (2025). أبحاث في تاريخ السلطنة القعيطية الحضرمية. المكلا: منشورات المركز.",
      citationChicago: "مركز حضرموت للدراسات التاريخية والتوثيق والنشر. أبحاث في تاريخ السلطنة القعيطية الحضرمية. المكلا: منشورات المركز، 2025.",
      citationMLA: "مركز حضرموت للدراسات التاريخية والتوثيق والنشر. أبحاث في تاريخ السلطنة القعيطية الحضرمية. 2025.",
      featured: true
    },
    {
      id: "bk-9156",
      slug: "ports-of-hadhramout-sumhuram",
      titleAr: "موانئ حضرموت القديمة: ميناء سمهرم (خور روري) أنموذجاً",
      titleEn: "Ancient Ports of Hadhramout: Sumhuram (Khor Rori) as a Model",
      authorAr: "د. سالم صالح باسردة",
      authorEn: "Dr. Salem Saleh Basarda",
      category: "ports-trade",
      categoryAr: "الموانئ والتجارة القديمة",
      categoryEn: "Ancient Maritime Trade",
      year: 2025,
      hijriYear: 1446,
      pages: 290,
      isbn: "978-9923-81-001-8",
      coverImage: "https://files.hadramout.center/media/2025/12/موانئ-حضرموت-مركز-حضرموت3-scaled.jpg",
      abstractAr: "بحث في تاريخ ميناء سمهرم التاريخي من القرن الثالث قبل الميلاد حتى القرن الثالث الميلادي، موضحاً كيف شكل هذا الميناء الشريان الرئيسي لتصدير اللبان الحضرمي إلى روما ومصر وبلاد الرافدين والهند.",
      abstractEn: "Archaeological and historical inquiry into Sumhuram Port (3rd c. BCE to 3rd c. CE), demonstrating how it functioned as the primary frankincense trade nexus linking South Arabia to Rome, Egypt, and India.",
      citationAPA: "باسردة، س. ص. (2025). موانئ حضرموت القديمة: ميناء سمهرم أنموذجاً. المكلا: مركز حضرموت.",
      citationChicago: "باسردة، سالم صالح. موانئ حضرموت القديمة: ميناء سمهرم أنموذجاً. المكلا: مركز حضرموت للدراسات التاريخية، 2025.",
      citationMLA: "باسردة، سالم صالح. موانئ حضرموت القديمة: ميناء سمهرم أنموذجاً. مركز حضرموت، 2025.",
      featured: true
    },
    {
      id: "bk-9154",
      slug: "hadhramis-in-islamic-state",
      titleAr: "دور الحضارمة في بناء الدولة الإسلامية في صدر الإسلام وعصر بني أمية",
      titleEn: "The Role of Hadhramis in Building the Islamic State in Early Islam and the Umayyad Era",
      authorAr: "د. عبد الله محمد بن ثعلب",
      authorEn: "Dr. Abdullah Mohammed Bin Thalab",
      category: "islamic",
      categoryAr: "التاريخ الإسلامي المبكر",
      categoryEn: "Early Islamic History",
      year: 2025,
      hijriYear: 1446,
      pages: 340,
      isbn: "978-9923-81-000-1",
      coverImage: "https://files.hadramout.center/media/2025/12/غلاف-كتاب-دور-الحضارمة-في-بناء-الدولة-الإسلامية3-scaled.jpg",
      abstractAr: "توثيق شامل لمشاركات القبائل والأعلام الحضارمة في الفتوحات الإسلامية، وتأسيس الأمصار في الكوفة والفسطاط والقيروان، وإسهاماتهم الإدارية والعلمية في عهد الخلفاء الراشدين والدولة الأموية.",
      abstractEn: "Comprehensive documentation of Hadhrami tribes and figures in early Islamic expansions, the founding of garrison cities (Fustat, Kufa, Kairouan), and their administrative jurisprudence under the Umayyads.",
      citationAPA: "بن ثعلب، ع. م. (2025). دور الحضارمة في بناء الدولة الإسلامية. المكلا: مركز حضرموت.",
      citationChicago: "بن ثعلب، عبد الله محمد. دور الحضارمة في بناء الدولة الإسلامية. المكلا: مركز حضرموت للدراسات التاريخية، 2025.",
      citationMLA: "بن ثعلب، عبد الله محمد. دور الحضارمة في بناء الدولة الإسلامية. مركز حضرموت، 2025.",
      featured: false
    }
  ],

  forumEvents: [
    {
      id: "forum-551",
      titleAr: "إشراقات مرسالية في تاريخ الفكر الحضرمي",
      titleEn: "Missionary Illuminations in the Intellectual History of Hadhramout",
      speakerAr: "الأستاذ خالد القحوم (باحث ومفكر)",
      speakerEn: "Mr. Khaled Al-Qahoum (Scholar and Thinker)",
      dateAr: "سبتمبر 2026",
      dateEn: "September 2026",
      locationAr: "قاعة منتدى عميد الوفاء الثقافي، مقر المركز، المكلا",
      locationEn: "Ameed Al-Wafa Cultural Hall, Center HQ, Mukalla",
      summaryAr: "سلطت المحاضرة الضوء على الرسائل الفكرية والأخلاقية للمصلحين الحضارمة في أواخر القرن التاسع عشر ومطلع القرن العشرين، ودورهم في صياغة الشخصية الحضرمية المعتدلة ونشر ثقافة الحوار.",
      summaryEn: "The lecture illuminated the ethical and intellectual treatises of late 19th and early 20th-century Hadhrami reformers, emphasizing their role in fostering moderate cultural dialogue.",
      status: "completed"
    },
    {
      id: "forum-550",
      titleAr: "المشروع الحضاري في أدب علي أحمد باكثير",
      titleEn: "The Civilizational Vision in the Literature of Ali Ahmad Bakathir",
      speakerAr: "د. عبد الحكيم الزبيدي (ناقد وأكاديمي)",
      speakerEn: "Dr. Abdulhakim Al-Zubaidi (Literary Critic)",
      dateAr: "نوفمبر 2025",
      dateEn: "November 2025",
      locationAr: "المكلا — منتدى عميد الوفاء",
      locationEn: "Mukalla — Ameed Al-Wafa Forum",
      summaryAr: "قراءة نقدية في مسرحيات وروايات الأديب الكبير علي أحمد باكثير الحضرمي الأصل والمنشأ، وكيف عبّر عن تطلعات الأمة العربية والإسلامية وقيم الحرية والعدالة.",
      summaryEn: "Critical analysis of the dramatic and novelistic works of prominent Hadhrami writer Ali Ahmad Bakathir, examining his articulation of freedom, human justice, and heritage.",
      status: "completed"
    }
  ],

  timelineMilestones: [
    {
      era: "ancient",
      eraLabelAr: "العصور القديمة (مملكة حضرموت)",
      eraLabelEn: "Ancient Era (Kingdom of Hadhramout)",
      yearLabelAr: "الألفية الأولى قبل الميلاد – القرن الثالث الميلادي",
      yearLabelEn: "1st Millennium BCE – 3rd Century CE",
      titleAr: "ازدهار مملكة حضرموت وطريق اللبان وميناء سمهرم",
      titleEn: "The Zenith of the Kingdom of Hadhramout & the Frankincense Route",
      descriptionAr: "شهدت هذه الحقبة تأسيس عاصمة المملكة في شبوة القديمة، وتشييد موانئ الملاحة الدولية في قنا (بئر علي) وسمهرم (ظفار)، حيث صدرت حضرموت أجود أنواع اللبان والبخور إلى معابد مصر القديمة وروما وبابل.",
      descriptionEn: "Marked by the establishment of the capital at ancient Shabwa and the founding of major international ports at Qana and Sumhuram, establishing Hadhramout as the frankincense hub of antiquity."
    },
    {
      era: "islamic",
      eraLabelAr: "العصر الإسلامي المبكر",
      eraLabelEn: "Early Islamic Era",
      yearLabelAr: "القرن الأول الهجري / السابع الميلادي",
      yearLabelEn: "7th Century CE / 1st Century AH",
      titleAr: "وفود أهل حضرموت إلى المدينة المنورة ودورهم في الفتوحات",
      titleEn: "The Hadhrami Delegations to Medina & Roles in Early Expansion",
      descriptionAr: "وفد زعماء حضرموت ومنهم وائل بن حجر الكندي إلى النبي ﷺ، وسرعان ما أصبح المقاتلون والعلماء الحضارمة ركائز أساسية في فتوحات بلاد الشام ومصر وشمال أفريقيا، واشتهروا بالقضاء والعلم والتجارة.",
      descriptionEn: "Hadhrami delegations pledged allegiance in Medina; Hadhrami scholars and warriors subsequently became foundational administrators and jurists in Syria, Egypt, and North Africa."
    },
    {
      era: "diaspora",
      eraLabelAr: "عصر الهجرات الكبرى",
      eraLabelEn: "Era of Global Oceanic Migration",
      yearLabelAr: "من القرن الرابع عشر إلى القرن التاسع عشر الميلادي",
      yearLabelEn: "14th – 19th Century CE",
      titleAr: "الهجرة الحضرمية إلى جنوب شرق آسيا وشرق أفريقيا والهند",
      titleEn: "The Hadhrami Diaspora in Southeast Asia, East Africa & India",
      descriptionAr: "انطلق التجار والدعاة الحضارمة بحراً عبر المحيط الهندي ليستقروا في إندونيسيا، وماليزيا، وسنغافورة، وحيدر أباد، وزنجبار، وكينيا، مسهمين بأسلوبهم الأخلاقي في نشر الإسلام السلمي وإثراء التجارة والثقافة.",
      descriptionEn: "Hadhrami merchants and scholars crossed the Indian Ocean to settle in modern Indonesia, Malaysia, Singapore, Zanzibar, and India, spreading peaceful commerce and civic leadership."
    },
    {
      era: "sultanates",
      eraLabelAr: "عصر السلطنات والتحديث الإداري",
      eraLabelEn: "The Sultanates & Administrative Modernization",
      yearLabelAr: "1881 – 1967م",
      yearLabelEn: "1881 – 1967 CE",
      titleAr: "قيام السلطنة القعيطية والسلطنة الكثيرية وتأسيس التعليم النظامي",
      titleEn: "Rise of the Qu'aiti and Kathiri Sultanates & Modern Statehood",
      descriptionAr: "تميزت هذه الحقبة ببناء المؤسسات المدنية الحديثة في المكلا وسيئون والشحر، وصك العملات الخاصة، وتأسيس المدارس النظامية وجيش البادية النظامي، وصدور أولى الصحف والمجلات الثقافية الحضرمية.",
      descriptionEn: "Characterized by modern civic institutions in Mukalla and Seiyun, distinct coinage, modern formal schooling, the Hadhrami Bedouin Legion, and early cultural periodicals."
    },
    {
      era: "modern",
      eraLabelAr: "المعاصرة والتوثيق الأكاديمي",
      eraLabelEn: "Contemporary Era & Scientific Documentation",
      yearLabelAr: "منذ مطلع الألفية حتى اليوم",
      yearLabelEn: "2000s – Present",
      titleAr: "تأسيس مركز حضرموت وإحياء حركة التوثيق والنشر الأكاديمي",
      titleEn: "Founding of the Hadhramout Center & Resurgence of Archival Research",
      descriptionAr: "تأسيس مركز حضرموت للدراسات التاريخية والتوثيق والنشر ليكون المنبر المنهجي المعني بجمع التراث، وإصدار مجلة حضرموت الثقافية (40+ عدداً)، وعقد المؤتمرات التاريخية الدولية لخدمة الهوية الحضرمية.",
      descriptionEn: "Establishment of the Hadhramout Center to serve as the premier methodological body safeguarding archival records, publishing over 40 magazine issues, and hosting academic conferences."
    }
  ],

  media: [
    {
      id: "media-1",
      type: "podcast",
      seriesAr: "بودكاست سقاية",
      seriesEn: "Siqayah Podcast",
      titleAr: "سقاية | الحلقة 1: تجارة البخور والملاحة التاريخية في بحر العرب",
      titleEn: "Siqayah | Ep. 1: Frankincense Trade and Maritime History in the Arabian Sea",
      guestAr: "د. عبد القادر بن الشيخ علي باPermission",
      guestEn: "Dr. Abdulqader Al-Shaikh Ali Ba-Permission",
      duration: "34 دقيقة",
      dateAr: "فبراير 2026",
      dateEn: "Feb 2026",
      audioUrl: "https://files.hadramout.center/media/podcast-sample.mp3",
      coverImage: "https://files.hadramout.center/media/2026/02/img20260211_21160330-scaled.jpg",
      descriptionAr: "جلسة حوارية تستعرض المحطات البحرية في قنا والشحر وشبكة التجارة القديمة التي ربطت حضرموت ببلاد الهند وسيلان وشرق إفريقيا.",
      descriptionEn: "A scholarly dialogue exploring ancient maritime ports of Qana and Shihr and trade routes connecting Hadhramout with India and East Africa."
    },
    {
      id: "media-2",
      type: "video",
      seriesAr: "برنامج كاتب وكتاب",
      seriesEn: "Author & Book Series",
      titleAr: "كاتب وكتاب | الحلقة 1: الدكتور أحمد باحارثة وكتاب جهود علماء حضرموت النحوية",
      titleEn: "Author & Book | Ep. 1: Dr. Ahmed Bahartha on Hadhrami Grammatical Contributions",
      guestAr: "د. أحمد باحارثة",
      guestEn: "Dr. Ahmed Bahartha",
      duration: "42 دقيقة",
      dateAr: "يناير 2026",
      dateEn: "Jan 2026",
      videoUrl: "https://www.youtube.com/watch?v=8mLzjsj-kw0",
      youtubeId: "8mLzjsj-kw0",
      coverImage: "https://i.ytimg.com/vi/8mLzjsj-kw0/hqdefault.jpg",
      descriptionAr: "حوار معمق يناقش فيه الباحث د. أحمد باحارثة كتابه الصادر عن المركز حول تحقيق ودراسة الموروث اللغوي والنحوي لعلماء حضرموت عبر العصور.",
      descriptionEn: "In-depth conversation with Dr. Ahmed Bahartha discussing his newly published monograph verifying the linguistic and grammatical heritage of Hadhrami scholars."
    },
    {
      id: "media-3",
      type: "video",
      seriesAr: "ندوات المركز الخارجية",
      seriesEn: "Center Regional Symposia",
      titleAr: "حضرموت الامتداد الجغرافي وذاكرة المكان — ندوة المركز بالرياض",
      titleEn: "Hadhramout: Geographic Horizon & Memory of Place — Riyadh Symposium",
      guestAr: "وفد باحثي مركز حضرموت بالرياض",
      guestEn: "Hadhramout Center Delegation in Riyadh",
      duration: "58 دقيقة",
      dateAr: "ديسمبر 2025",
      dateEn: "Dec 2025",
      videoUrl: "https://hadramout.center/videos/10158",
      youtubeId: "8mLzjsj-kw0",
      coverImage: "https://files.hadramout.center/media/2026/09/image-6.png",
      descriptionAr: "فعالية تاريخية وأكاديمية قدمها ممثلو المركز تناولت الملامح الجغرافية والتاريخية والمخطوطات الأهلية الحضرمية بحضور نخبة من المؤرخين.",
      descriptionEn: "A cultural and academic symposium reviewing the geographical, historical, and archival heritage of Hadhramout with leading regional historians."
    }
  ],

  translations: {
    ar: {
      navHome: "الرئيسية",
      navAbout: "عن المركز",
      navMagazines: "مجلة حضرموت",
      navBooks: "إصدارات الكتب",
      navConferences: "المؤتمرات",
      navForum: "منتدى عميد الوفاء",
      navTimeline: "خط التاريخ",
      navMedia: "الوسائط والبودكاست",
      navContact: "تواصل معنا",
      heroBadge: "مركز علمي مستقل · المكلا — حضرموت",
      heroTitle: "حفظُ الذاكرة وتوثيقُ الحضارة",
      heroSubtitle: "المنصة الرقمية المرجعية لمركز حضرموت للدراسات التاريخية والتوثيق والنشر بالمكلا — نوثق عمق التاريخ، وننشر أبحاث التراث، ونربط الباحثين بالذاكرة الوطنية الحضرمية.",
      exploreBooks: "تصفّح إصدارات الكتب",
      readMagazine: "طالع أعداد المجلة",
      searchPlaceholder: "ابحث في عناوين الكتب، المؤرخين، الأبحاث، وأعداد المجلة...",
      quickFilterAll: "الكل",
      quickFilterLinguistics: "التراث اللغوي",
      quickFilterSultanates: "تاريخ السلطنات",
      quickFilterPorts: "الموانئ والتجارة",
      quickFilterArchaeology: "الآثار والنقوش",
      quickFilterIslamic: "التاريخ الإسلامي",
      citeAPA: "اقتباس APA",
      citeChicago: "اقتباس Chicago",
      citeMLA: "اقتباس MLA",
      copiedToast: "تم نسخ الاقتباس الأكاديمي إلى الحافظة!",
      requestBook: "طلب اقتناء نسخة",
      downloadAbstract: "تحميل مستخلص البحث (PDF)",
      viewDetails: "التفاصيل والتوثيق",
      latestIssueBadge: "العدد الأخير الصادر",
      readIssue: "تفاصيل العدد وفهرسه",
      forumTitle: "منتدى عميد الوفاء الثقافي",
      forumSubtitle: "منبرٌ فكريٌّ دوريٌّ بالمكلا يناقش قضايا الفكر والمؤرخين ويحتفي بإسهامات الباحثين الحضارمة",
      timelineTitle: "موجز خط التاريخ الحضرمي",
      timelineSubtitle: "استكشف المحطات المفصلية التي صاغت تاريخ حضرموت عبر العصور",
      leadershipTitle: "الهيئة الإدارية والعلمية",
      departmentsTitle: "الأقسام والوحدات العلمية",
      contactTitle: "التواصل والاستفسار البحثي",
      contactSubtitle: "يسعد المركز باستقبال استفسارات الباحثين والجامعات وطلبات اقتناء الإصدارات",
      fullNameLabel: "الاسم الكامل",
      emailLabel: "البريد الإلكتروني",
      phoneLabel: "رقم الهاتف / واتساب",
      inquiryTypeLabel: "نوع الطلب",
      inquiryTypeGeneral: "استفسار عام",
      inquiryTypeBook: "طلب اقتناء إصدارات",
      inquiryTypeResearch: "استشارة بحثية وتوثيقية",
      messageLabel: "نص الرسالة أو تفاصيل الاستفسار",
      sendButton: "إرسال الاستفسار",
      formSuccessToast: "شكراً لتواصلك! سيتم الرد على استفسارك من قبل إدارة المركز في أقرب وقت.",
      addressTitle: "المقر الرئيسي للمركز:",
      rightsReserved: "جميع الحقوق محفوظة لمركز حضرموت للدراسات التاريخية والتوثيق والنشر",
      engineeredBy: "تصميم وهندسة المنصة: نوڤيكسا | Novixa (مبادرة الأثر الرقمي التطوعية)",
      mySavedList: "مكتبتي البحثية",
      exportRIS: "تنزيل مرجع Zotero (.RIS)",
      exportBibTeX: "تنزيل مرجع BibTeX (.bib)",
      themeDark: "الوضع الليلي الأكاديمي",
      themeLight: "الوضع النهاري",
      fontSizeLabel: "حجم الخط",
      bookmarkedToast: "تمت إضافة المرجع إلى مكتبتك البحثية!",
      removedBookmarkToast: "تمت إزالة المرجع من مكتبتك البحثية!",
      mediaEyebrow: "الإنتاج المرئي والمسموع",
      mediaTitle: "بودكاست سقاية والمكتبة المرئية",
      mediaSubtitle: "حوارات تاريخية موثقة ولقاءات علمية تسجل الذاكرة الحضرمية الشفهية والمكتوبة",
      shareBook: "مشاركة رابط الكتاب",
      printCard: "طباعة بطاقة التوثيق",
      copiedLinkToast: "تم نسخ الرابط المباشر للكتاب إلى الحافظة!"
    },
    en: {
      navHome: "Home",
      navAbout: "About the Center",
      navMagazines: "Hadramout Magazine",
      navBooks: "Publications",
      navConferences: "Conferences",
      navForum: "Ameed Al-Wafa Forum",
      navTimeline: "Historical Timeline",
      navMedia: "Media & Podcasts",
      navContact: "Contact Us",
      heroBadge: "Independent Scientific Center · Mukalla — Hadhramout",
      heroTitle: "Safeguarding Memory & Documenting Civilization",
      heroSubtitle: "The official digital platform of the Hadhramout Center for Historical Studies, Documentation and Publishing — Preserving deep heritage, publishing peer-reviewed research, and connecting scholars with South Arabian history.",
      exploreBooks: "Explore Publications",
      readMagazine: "Browse Magazine Issues",
      searchPlaceholder: "Search book titles, authors, research papers, and magazine volumes...",
      quickFilterAll: "All",
      quickFilterLinguistics: "Linguistics",
      quickFilterSultanates: "Sultanate History",
      quickFilterPorts: "Ports & Trade",
      quickFilterArchaeology: "Archaeology",
      quickFilterIslamic: "Islamic History",
      citeAPA: "Cite APA",
      citeChicago: "Cite Chicago",
      citeMLA: "Cite MLA",
      copiedToast: "Academic citation copied to clipboard!",
      requestBook: "Inquire / Acquire Book",
      downloadAbstract: "Download Abstract (PDF)",
      viewDetails: "Details & Metadata",
      latestIssueBadge: "Latest Published Volume",
      readIssue: "Read & Inspect Issue",
      forumTitle: "Ameed Al-Wafa Cultural Forum",
      forumSubtitle: "Periodic scholarly panels and intellectual lectures celebrating luminaries and historical themes",
      timelineTitle: "Chronological Timeline of Hadhramout",
      timelineSubtitle: "Key milestones that shaped Hadhrami identity from pre-Islamic antiquity to modern times",
      leadershipTitle: "Leadership & Scientific Committee",
      departmentsTitle: "Academic Departments & Facilities",
      contactTitle: "Research Inquiries & Contact",
      contactSubtitle: "The Center welcomes inquiries from researchers, universities, and cultural patrons",
      fullNameLabel: "Full Name",
      emailLabel: "Email Address",
      phoneLabel: "Phone / WhatsApp",
      inquiryTypeLabel: "Inquiry Type",
      inquiryTypeGeneral: "General Inquiry",
      inquiryTypeBook: "Book Acquisition Request",
      inquiryTypeResearch: "Research Consultation & Archival Access",
      messageLabel: "Message or Request Details",
      sendButton: "Submit Inquiry",
      formSuccessToast: "Thank you! Your inquiry has been sent to the Center's administrative team.",
      addressTitle: "Center Headquarters:",
      rightsReserved: "All rights reserved. Hadhramout Center for Historical Studies, Documentation and Publishing.",
      engineeredBy: "Platform engineered by Novixa (Pro Bono Digital Impact Initiative)",
      mySavedList: "Saved Bibliography",
      exportRIS: "Download Zotero / RIS (.ris)",
      exportBibTeX: "Download BibTeX (.bib)",
      themeDark: "Dark Academic Mode",
      themeLight: "Daylight Mode",
      fontSizeLabel: "Font Size",
      bookmarkedToast: "Reference added to your research bibliography!",
      removedBookmarkToast: "Reference removed from your research bibliography!",
      mediaEyebrow: "Audiovisual Archives",
      mediaTitle: "Siqayah Podcast & Video Library",
      mediaSubtitle: "Documentary dialogues and academic panels capturing living Hadhrami oral and archival history",
      shareBook: "Share Book Link",
      printCard: "Print Citation Card",
      copiedLinkToast: "Direct book link copied to clipboard!"
    }
  }
};
